name: Build Debug IPA

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    name: Build IPA
    runs-on: macos-13

    steps:

      - name: 1. Fetch Source Code
        uses: actions/checkout@v4


      - name: 2. Configure Xcode Environment
  uses: maxim-lobanov/setup-xcode@v1
  with:
    xcode-version: '15.4'


      - name: 3. Show Xcode
        run: |
          xcodebuild -version
          xcode-select -p


      - name: 4. Resolve Packages
        run: |
          xcodebuild \
          -resolvePackageDependencies \
          -project StikDebug.xcodeproj


      - name: 5. Compile Project Archive
        run: |
          xcodebuild clean archive \
            -project StikDebug.xcodeproj \
            -scheme "StikDebug" \
            -configuration Debug \
            -archivePath build/StikDebug.xcarchive \
            -sdk iphoneos \
            -destination 'generic/platform=iOS' \
            ONLY_ACTIVE_ARCH=NO \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_ALLOWED=NO


      - name: 6. Package IPA
        run: |
          mkdir -p Payload
          cp -R build/StikDebug.xcarchive/Products/Applications/StikDebug.app Payload/
          zip -r StikDebug.ipa Payload


      - name: 7. Upload IPA
        uses: actions/upload-artifact@v4
        with:
          name: StikDebug-IPA
          path: StikDebug.ipa
